##########################################################################################################################
# Database Configuration

# Connection string is in Go pq driver format:
# host=<host> port=<port> user=<databaseUser>
# password=<databasePassword> dbname=<databaseName>

[database]

connection_string = "host= port= user= password= dbname= sslmode=disable"
max_idle_connection = 5
max_open_connections = 20
connection_max_lifetime = "60s"
driver_name = "postgres"
##########################################################################################################################
# HTTP server configuration

[http]

server_address = ":8080"
##########################################################################################################################